{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    audacity
    vesktop
    nodejs
    obs-studio
    vscode-fhs
    direnv
    inputs.zen-browser.packages."${system}".default
    spotify
    blender
    devenv
    mkvtoolnix
    aegisub
    godot
    heroic
    lutris
    protonup-qt
    protontricks
    brave
    qbittorrent
    openmw
    hydralauncher
    bzip2
    nixfmt-rfc-style
    nil
    vlc
    (xivlauncher-rb.override { useGameMode = true; })
    #kdePackages.ark
    #kdePackages.dolphin
    winetricks
    wine
    jellyfin-media-player
  ];
}